### ISSUE TITLE
Could not understand output of pdfimages

### ISSUE THREAD

**Issue by kundor** [virantha/pypdfocr#28]
Running pypdfocr 0.8.2, it says:

    WARNING: Could not understand output of pdfimages, please rerun with -d option and file an issue at http://github.com/virantha/pypdfocr/issues

So, here I am. The issue seems to be that the image type reported by `pdfimages` is "stencil" and not "image." The output of `pdfimages -list file.pdf` begins like so:

    page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
    --------------------------------------------------------------------------------------------
       1     0 stencil  2528  3200  -       1   1  ccitt  no         8  0   301   301 27.2K 2.8%
       2     1 stencil  2528  3200  -       1   1  ccitt  no         9  0   301   301 45.9K 4.7%

**Comment by gameslammer7** [comment]
Okay, I also have this issue. I managed to figure out how to send the output I was seeing to a log so that I can actually read into what is going on. Oddly, I still had to kill the window because it wanted to keep running in some sort of loop (you can probably tell from the repeated line `pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork`.

Anyway. Here is the full log.

```
Using Ghostscript: "c:\Program Files\gs\gs9.16\bin\gswin64c.exe"
Running pdfimages to figure out DPI...
pdfimages -list "ImageOnly.pdf"
   1     0 stencil  2495  3501  -       1   1  ccitt  no         8  0   

319   319 23.6K 2.2%
Detected greyscale
"c:\Program Files\gs\gs9.16\bin\gswin64c.exe" -q -dNOPAUSE -

sDEVICE=jpeggray -dJPEGQ=75 -r300 -sOutputFile="ImageOnly_%d.jpg" 

"ImageOnly.pdf" -c quit
Created image ImageOnly_1.jpg
Starting preprocessing parallel execution
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 44, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\socket", line 47, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 409, in load_module
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 46, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\email.utils", line 27, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 879, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 97, in __init__
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 111, in seed
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\PIL.PpmImagePlugin", line 20, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 202, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_archive.py", line 317, in extract
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\PIL.PngImagePlugin", line 40, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\PIL.Image", line 53, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 409, in load_module
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\argparse", line 86, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 158, in find_module
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 46, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\email.utils", line 40, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 387, in find_module
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\yaml", line 8, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\yaml.loader", line 4, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\yaml.reader", line 45, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\yaml.reader", line 137, in Reader
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\re", line 190, in compile
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\re", line 240, in _compile
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 505, in compile
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 487, in _code
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 465, in _compile_info
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 184, in _compile_charset
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 227, in _optimize_charset
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\sre_compile", line 347, in _optimize_unicode
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 44, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\socket", line 47, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 409, in load_module
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 46, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\email.utils", line 29, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\urllib", line 33, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\urlparse", line 120, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\collections", line 360, in namedtuple
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 46, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\email.utils", line 27, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 879, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 97, in __init__
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\random", line 111, in seed
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 28, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\pypdfocr_pdf", line 41, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\reportlab.pdfgen.canvas", line 21, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\reportlab.pdfbase.pdfdoc", line 22, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\reportlab.pdfbase.pdfmetrics", line 22, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\reportlab.pdfbase._fontdata", line 197, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 202, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_archive.py", line 317, in extract
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 44, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\socket", line 53, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 409, in load_module
KeyboardInterrupt
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\smtplib", line 44, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 270, in load_module
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows

\out00-PYZ.pyz\socket", line 47, in <module>
  File "C:\Users\Virantha Ekanayake\dev\pyinstaller\PyInstaller\loader

\pyi_importers.py", line 409, in load_module
KeyboardInterrupt
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
usage: pypdfocr.exe [-h] [-d] [-v] [-m] [-l LANG] [--skip-preprocess]
                    [-w WATCH_DIR] [-f] [-c CONFIGFILE] [-e] [-n]
                    [pdf_filename]
pypdfocr.exe: error: unrecognized arguments: --multiprocessing-fork
Starting conversion of ImageOnly.pdf
WARNING: Could not understand output of pdfimages, please rerun with -d 

option and file an issue at http://github.com/virantha/pypdfocr/issues
^C
```

I would really like to be able to use this script for my work, so any help in figuring out how to get this to work on Windows 7 64-bit will be greatly appreciated.

Thanks,
Troy

**Comment by chrisb86** [comment]
Same here...

**Comment by virantha** [comment]
Can someone provide a testcase pdf?

**Comment by januweness** [comment]
[test.pdf](https://github.com/virantha/pypdfocr/files/2976985/test.pdf)
Hi, same issue here under Ubuntu, and attached a test pdf file.

**Comment by aferjani** [comment]
> [test.pdf](https://github.com/virantha/pypdfocr/files/2976985/test.pdf)
> Hi, same issue here under Ubuntu, and attached a test pdf file.

I think the page in the pdf file is text and not an image. 
If you use a pdf file that contains an image, it could extract dpi and run without errors, otherwise, it will use default dpi (set to 300)
