### ISSUE TITLE
Install without evernote support

### ISSUE THREAD

**Issue by oksigma** [virantha/pypdfocr#55]
Trying to install using OSX and receive the following errors.

from pip install pypdfocr

Collecting evernote (from pypdfocr)
  Using cached evernote-1.25.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kh/2lch691x54504lc1jm_l9j7h0000gn/T/pip-build-inmeraj3/evernote/setup.py", line 6
        exec x

from python setup.py install

File "/tmp/easy_install-cz2a5as6/evernote-1.25.2/setup.py", line 6
    exec x

**Comment by getglad** [comment]
Similar on Win7:
```
File "<string>", line 1, in <module>
File "...\AppData\Local\Temp\pip-build-f_cxhta5\evernote\setup.py", line 6
  exec 6

SyntaxError: Missing parantheses in call to 'exec'
```

Update: If I use my Python 2 env it works. Good argument for https://github.com/virantha/pypdfocr/issues/36

**Comment by virantha** [comment]
Pypdfocr is not supported under Python3.  I do not have time to port right now.  If someone wants to submit a pull with Python 3 updates with new tests and keep Python 2 compatibility, I would be happy to integrate.
