### ISSUE TITLE
Can't install on mac 

### ISSUE THREAD

**Issue by hjanjua** [virantha/pypdfocr#73]
Error: SyntaxError: Missing parentheses in call to 'exec' while install evernote

**Comment by bruno-robert** [comment]
I've been getting the same error when trying to install pypdfocr with `pip install pypdfocr` on OSX.
The problem seems to occur when pypdfocr tries to install the Evernote. In python 2.7, exec is written without parentheses but in python 3.x I think it's supposed to have them (and that is where the problem is coming from). Maybe adding a version of pypdfocr without Evernote support could be a quick fix.

copy/paste of the said error

```
Collecting evernote (from pypdfocr)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f9/6b/877f8edef8ef040d32eb38f3bf6322ba334de9d10614d8db9d869c162fc1/evernote-1.25.3.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 5.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kb/j3dk_36n2wqc7dz9j74bv6rc0000gn/T/pip-build-l8c0pef2/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
```

**Comment by him1532** [comment]
Trying to install on my mac running macOS 13.0.1
When I execute `pip install pypdfocr` following is the output

> `Collecting pypdfocr
>   Using cached pypdfocr-0.9.1.tar.gz (43 kB)
>   Preparing metadata (setup.py) ... done
> Collecting pillow>=2.2 (from pypdfocr)
>   Obtaining dependency information for pillow>=2.2 from https://files.pythonhosted.org/packages/07/22/93d6b5aa5917d09ec7088a2c4d1821848f3f95fbdc2633ba9d9fc28444a1/Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata
>   Using cached Pillow-10.1.0-cp311-cp311-macosx_10_10_x86_64.whl.metadata (9.5 kB)
> Collecting reportlab>=2.7 (from pypdfocr)
>   Obtaining dependency information for reportlab>=2.7 from https://files.pythonhosted.org/packages/44/2c/f09a5abefa8f2b575acfc19ed4536a365ef0432ae3bce94a57a2de9b4f52/reportlab-4.0.8-py3-none-any.whl.metadata
>   Using cached reportlab-4.0.8-py3-none-any.whl.metadata (1.4 kB)
> Collecting watchdog>=0.6.0 (from pypdfocr)
>   Using cached watchdog-3.0.0-cp311-cp311-macosx_10_9_x86_64.whl (91 kB)
> Collecting pypdf2>=1.23 (from pypdfocr)
>   Using cached pypdf2-3.0.1-py3-none-any.whl (232 kB)
> Collecting evernote (from pypdfocr)
>   Using cached evernote-1.25.3.tar.gz (141 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/private/var/folders/s9/w16trxt88v56j0008k8dr4p00000gp/T/pip-install-c597a7cn/evernote_39563441d5264bc79f8511483beec897/setup.py", line 6
>           exec x
>           ^^^^^^
>       SyntaxError: Missing parentheses in call to 'exec'. Did you mean exec(...)?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.`
